# Build arguments
ARG SOURCE_CODE=.
 
# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:1.22@sha256:703937e152d049e62f5aa8ab274a4253468ab70f7b790d92714b37cf0a140555 as builder
 
## Build args to be used at this step
ARG SOURCE_CODE
 
WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -a -o manager cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0
 
WORKDIR /
COPY --from=builder /workspace/manager .
 
USER 65532:65532
ENTRYPOINT ["/manager"]
 
LABEL com.redhat.component="odh-model-registry-operator-container" \
      name="managed-open-data-hub/odh-model-registry-operator-rhel8" \
      description="Manages lifecycle of RHOAI Model Registry custom resources and associated Kubernetes resources" \
      summary="odh-model-registry-operator-container" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-model-registry-operator-container" \
      io.k8s.description="odh-model-registry-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
